# Generated by Django 4.0.1 on 2022-01-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_address_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
